
services:
  redis:
    image: redis:7
    command: redis-server --save "" --appendonly no

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    depends_on:
      - redis
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    command: celery -A app.tasks worker --loglevel=info
    env_file: .env
    depends_on:
      - redis

  streamlit:
    build:
      context: .
      dockerfile: ui/Dockerfile
    environment:
      - API_BASE=http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"
