version: '3.8'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.vm-builder
    image: s2os
    container_name: s2os_builder
    volumes:
      - ./vm:/app/vm
    platform: linux/amd64
    entrypoint: ["/app/build-vm.sh"]

  qemu-vm:
    build:
      context: .
      dockerfile: Dockerfile.qemu-runner
    image: simsecureos-qemu
    container_name: s2os_qemu
    depends_on:
      - builder
    volumes:
      - ./vm:/vm
    tty: true
    stdin_open: true
    platform: linux/amd64

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    image: s2os_ui
    container_name: s2os_ui_container
    ports:
      - "8501:8501"
    volumes:
      - ./plugins:/app/plugins
      - ./vm:/app/vm
      - ./attack_history.csv:/app/attack_history.csv
    depends_on:
      - builder
    command: streamlit run app.py --server.address=0.0.0.0
