FROM debian:bullseye

RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    unzip \
    curl \
    bc \
    git \
    cpio \
    rsync \
    file \
    python3 \
    libncurses-dev \
    xz-utils \
    tar \
    qemu-system-x86 \
    gawk \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY build-vm.sh .

RUN chmod +x build-vm.sh

ENTRYPOINT ["./build-vm.sh"]
